embeddings: {name: BAAI/bge-base-en-v1.5, dim: 768}
reranker:
  name: BAAI/bge-reranker-v2-m3
  device: "auto"
  fallback: cross-encoder/ms-marco-MiniLM-L-6-v2

llm:
  strategy_order: ["local_hf", "openai_compat"]
  local_hf:
    model_path: microsoft/Phi-3-mini-4k-instruct
    allow_remote: true
    dtype: float16   # set to float32 for CPU-only environments
    device_map: auto
    token_env: HF_TOKEN  # set this env var if the repo requires gated access
    max_new_tokens: 512
    temperature: 0.0
    stop: ["<|ATTR_CARD|>"]
  openai_compat:
    endpoint_env: LLM_ENDPOINT
    api_key_env: LLM_API_KEY
    model: "microsoft/Phi-3-mini-4k-instruct"
    max_tokens: 900
    temperature: 0.0
    stop: ["<|ATTR_CARD|>"]
